name: Merge Feature to Dev
on:
  push:
    branches:
      - 'feature/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Merge feature/changes -> dev
        uses: devmasx/merge-branch@develop
        with:
          type: now
          target_branch: develop
          github_token: ${{ secrets.GIT_TOKEN }}
